[plugins]
algomate = { id = "org.tudalgo.algomate", version = "0.7.1" }
style = { id = "org.sourcegrade.style", version = "3.0.0" }
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }


[libraries]
fopbot = { module = "org.tudalgo:fopbot", version = "0.8.1" }
junit-core = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.2" }
